default_language_version:
  # force all unspecified python hooks to run python3
  python: python3.10
minimum_pre_commit_version: '2.20.0'
repos:
  # fixers
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/hhatto/autopep8
    rev: 'v2.0.4'
    hooks:
      - id: autopep8
        args: [
          '--in-place',
          '--select',
          'E101,E112,E113,E115,E116,E117,E121,E122,E123,E124,E125,E126,E127,E128,E129,E131,E133,E201,E202,E203,E211,E221,E222,E223,E224,E225,E226,E227,E228,E231,E231,E241,E242,E251,E252,E261,E262,E265,E271,E272,E273,E274,E275,E301,E302,E303,E304,E305,E306,W391,W504'
        ]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
        exclude: '\/migrations\/'
        args: ['--py36-plus']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: double-quote-string-fixer
        exclude: '\/migrations\/'
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
        types: [python]
      - id: mixed-line-ending
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: ['--py3-plus', '--py38-plus']

  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.15.0"
    hooks:
    -   id: django-upgrade
        args: [--target-version, "4.1"]   # Replace with Django version
  # linters
  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.5.0
    hooks:
      - id: validate_manifest
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==23.12.2
          - flake8-no-pep420==2.7.0
          - flake8-encodings==0.5.1
